// Bar / Bebidas — compact lists. Per brief, render restrained editorial subsections.

export type BarItem = { name: string; price: number };
export type BarSection = {
  key: string;
  title: string;
  items: BarItem[];
};

export const BAR_SECTIONS: BarSection[] = [
  {
    key: "refrescos",
    title: "Refrescos y Zumos",
    items: [
      { name: "Agua 1/2 L", price: 2.7 },
      { name: "Refrescos", price: 3.0 },
      { name: "Zumos", price: 3.2 },
      { name: "Aquarius", price: 3.4 },
      { name: "Nestea", price: 3.4 },
      { name: "Agua con gas", price: 3.7 },
      { name: "Zumo natural", price: 3.8 },
    ],
  },
  {
    key: "cervezas",
    title: "Cervezas",
    items: [
      { name: "Caña Victoria", price: 2.7 },
      { name: "Victoria · Estrella Damm · Cruzcampo", price: 3.2 },
      { name: "Daura sin gluten", price: 3.5 },
      { name: "Heineken", price: 3.8 },
      { name: "Alhambra", price: 4.0 },
      { name: "Coronita", price: 4.0 },
      { name: "Pinta Victoria", price: 5.4 },
      { name: "Jarra Victoria 1L", price: 10.8 },
    ],
  },
  {
    key: "aperitivos",
    title: "Aperitivos",
    items: [
      { name: "Copa Albariño Casa", price: 4.6 },
      { name: "Copa Cava", price: 5.2 },
      { name: "Martini", price: 6.0 },
      { name: "Vermouth Lustau", price: 6.0 },
      { name: "Campari con soda o naranja", price: 8.0 },
      { name: "Tinto de verano", price: 3.4 },
      { name: "Pinta Tinto verano", price: 6.8 },
      { name: "Jarra litro Tinto verano", price: 13.6 },
      { name: "Vaso Sangría", price: 4.7 },
      { name: "Pinta Sangría", price: 9.4 },
      { name: "Jarra Sangría", price: 19.0 },
      { name: "Jarra Sangría de Cava", price: 24.0 },
    ],
  },
  {
    key: "cafe",
    title: "Café e Infusiones",
    items: [
      { name: "Café solo", price: 2.3 },
      { name: "Café con leche", price: 2.3 },
      { name: "Infusión", price: 2.3 },
      { name: "Capuchino", price: 3.3 },
      { name: "Carajillo", price: 3.3 },
      { name: "Café irlandés", price: 8.2 },
    ],
  },
  {
    key: "brandies",
    title: "Brandies y Coñacs",
    items: [
      { name: "Soberano", price: 5.0 },
      { name: "Magno", price: 5.0 },
      { name: "Carlos III", price: 5.0 },
      { name: "Torres V", price: 6.0 },
      { name: "Torres 10", price: 8.0 },
      { name: "Carlos I", price: 9.0 },
      { name: "Cardenal Mendoza", price: 10.0 },
      { name: "Courvoisier VSOP", price: 12.0 },
      { name: "Lepanto", price: 12.0 },
      { name: "Larios 1866", price: 15.0 },
      { name: "Carlos I Imperial XO", price: 16.0 },
      { name: "Gran Duque de Alba", price: 16.0 },
      { name: "Rémy Martin", price: 16.0 },
      { name: "Luis Felipe", price: 25.0 },
    ],
  },
  {
    key: "licores",
    title: "Licores",
    items: [
      { name: "Melocotón · Mora · Manzana · Anís dulce", price: 4.5 },
      { name: "Marie Brizard", price: 5.0 },
      { name: "Hierbas · Orujo · Limoncello · Baileys · Grappa · Frangélico · Fernet · Amaretto", price: 5.5 },
      { name: "Pacharán · Cointreau · Licor 43 · Tía María · Jagermeister", price: 6.0 },
      { name: "Grand Marnier Rojo", price: 7.5 },
      { name: "Drambuie", price: 8.5 },
    ],
  },
  {
    key: "ginebras",
    title: "Ginebras",
    items: [
      { name: "Bombay · Tanqueray · Beefeater · Larios · Gordons · Tanqueray 0,0 · Seagrams", price: 8.0 },
      { name: "Larios 12 · Beefeater Pink · Larios Rose", price: 8.5 },
      { name: "Bombay Sapphire · Puerto de Indias", price: 9.0 },
      { name: "Tribute · Ginraw · Macaronnesian · Rives Especial · Mombasa · Rives 1880 · Wingy", price: 10.0 },
      { name: "Martin Miller · Rives Pink · Beefeater 24", price: 10.5 },
      { name: "Roku · London nº1 · Nordes", price: 11.0 },
      { name: "G'vine · Hendricks", price: 11.5 },
      { name: "Citadelle Reserva · Hendricks Lunar · Stars Bombay · Mombasa Rosa · The Botanical's · Tanqueray Ten · Brockmans · Bulldog · Gin Mare", price: 12.0 },
      { name: "Martins Millers 9 Moons · Hendricks Midsummers · Gin Mare Capri", price: 14.0 },
      { name: "Beefeater Burrough's Reserve · G'Vine Nouaison · Monkey 47", price: 15.0 },
    ],
  },
  {
    key: "rones",
    title: "Rones",
    items: [
      { name: "Bacardi · Cacique · Barceló · Brugal · Legendario · Habana 5 años", price: 8.0 },
      { name: "Diplomático · Pampero", price: 9.0 },
      { name: "Habana 7 años · Arehucas Oro · Kraken", price: 9.5 },
      { name: "Brugal Extra Viejo · Cacique 500", price: 10.5 },
      { name: "Barceló Imperial", price: 11.0 },
      { name: "Matusalén 15 · Flor de Caña 12 · Pampero Aniversario", price: 12.0 },
      { name: "Brugal 1888", price: 12.5 },
      { name: "Brugal Siglo Oro", price: 15.0 },
      { name: "Barceló Imperial Ónix", price: 16.0 },
      { name: "Zacapa 23", price: 17.0 },
      { name: "Matusalén 23", price: 21.0 },
      { name: "Zacapa XO", price: 27.0 },
      { name: "Zacapa Royal", price: 42.0 },
    ],
  },
  {
    key: "vodkas",
    title: "Vodkas",
    items: [
      { name: "Smirnoff · Absolut", price: 8.0 },
      { name: "Moskovskaya", price: 9.0 },
      { name: "Cîroc · Stolichnaya · Absolut Elyx", price: 11.0 },
      { name: "Belvedere", price: 13.0 },
      { name: "Beluga · Grey Goose", price: 13.5 },
      { name: "Roberto Cavalli", price: 14.0 },
      { name: "Beluga Transatlantic", price: 14.5 },
      { name: "Beluga Gold Line", price: 20.0 },
    ],
  },
  {
    key: "whiskies",
    title: "Whiskies",
    items: [
      { name: "DYC 8 · Ballantines · Passport · JB · White Label · Cutty Sark · Johnnie Walker", price: 8.0 },
      { name: "Jameson", price: 9.0 },
      { name: "Lagavulin 8", price: 10.0 },
      { name: "JW Etiqueta Negra", price: 10.5 },
      { name: "Chivas Regal 12 · JB 15", price: 12.0 },
      { name: "Golden Label", price: 12.5 },
      { name: "Cardhú 12", price: 13.0 },
      { name: "Glenfiddich 12", price: 14.0 },
      { name: "Chivas XV · Chivas 18 · Lagavulin 16", price: 15.0 },
      { name: "Jack Daniel's Gentleman", price: 15.5 },
      { name: "Green Label", price: 18.5 },
      { name: "Glenfiddich 21", price: 19.0 },
      { name: "Macallan 12 · Chivas 21", price: 20.0 },
      { name: "Macallan 15", price: 23.0 },
      { name: "Hibiki", price: 26.0 },
      { name: "Macallan Estate", price: 28.0 },
      { name: "Blue Label", price: 32.0 },
      { name: "Macallan Rare Cask", price: 37.0 },
    ],
  },
];
