// AUTO-GENERATED by scripts/download-dish-photos.mjs.
// Maps a slugified dish name to its photo path under /public/.
// Re-run `node scripts/download-dish-photos.mjs` to refresh.

export const DISH_PHOTOS: Record<string, string> = {
  "aguacate-con-langostinos": "/assets/photos/dishes/aguacate-con-langostinos.jpg",
  "arroz-a-banda": "/assets/photos/dishes/arroz-a-banda.jpg",
  "arroz-con-leche": "/assets/photos/dishes/arroz-con-leche.jpg",
  "arroz-negro": "/assets/photos/dishes/arroz-negro.jpg",
  "boquerones-al-limon": "/assets/photos/dishes/boquerones-al-limon.jpg",
  "busanos": "/assets/photos/dishes/busanos.jpg",
  "calamares-fritos": "/assets/photos/dishes/calamares-fritos.jpg",
  "coquinas": "/assets/photos/dishes/coquinas.jpg",
  "crema-catalana": "/assets/photos/dishes/crema-catalana.webp",
  "ensalada-cesar": "/assets/photos/dishes/ensalada-cesar.jpg",
  "ensalada-de-bonito-en-escabeche-con-tomate": "/assets/photos/dishes/ensalada-de-bonito-en-escabeche-con-tomate.jpg",
  "ensalada-de-la-casa": "/assets/photos/dishes/ensalada-de-la-casa.jpg",
  "ensalada-mixta": "/assets/photos/dishes/ensalada-mixta.jpg",
  "espetos-de-sardinas": "/assets/photos/dishes/espetos-de-sardinas.jpg",
  "langostinos-al-pil-pil": "/assets/photos/dishes/langostinos-al-pil-pil.jpg",
  "merluza-a-la-plancha": "/assets/photos/dishes/merluza-a-la-plancha.jpg",
  "milhoja-de-nata": "/assets/photos/dishes/milhoja-de-nata.jpg",
  "milhoja-de-turron": "/assets/photos/dishes/milhoja-de-turron.jpg",
  "mojito": "/assets/photos/dishes/mojito.jpg",
  "mojito-de-fresa": "/assets/photos/dishes/mojito-de-fresa.jpg",
  "paella-mixta": "/assets/photos/dishes/paella-mixta.jpg",
  "pate-de-mero": "/assets/photos/dishes/pate-de-mero.jpg",
  "pez-plata": "/assets/photos/dishes/pez-plata.jpg",
  "pina-colada": "/assets/photos/dishes/pina-colada.jpg",
  "pipirana-de-pulpo": "/assets/photos/dishes/pipirana-de-pulpo.jpg",
  "rosada-frita": "/assets/photos/dishes/rosada-frita.jpg",
  "salmon-a-la-caracola": "/assets/photos/dishes/salmon-a-la-caracola.jpg",
  "salmon-a-la-plancha": "/assets/photos/dishes/salmon-a-la-plancha.jpg",
  "salmonetitos-fritos": "/assets/photos/dishes/salmonetitos-fritos.jpg",
  "tarta-2-chocolates": "/assets/photos/dishes/tarta-2-chocolates.jpg",
  "tartar-de-salmon-con-aguacate": "/assets/photos/dishes/tartar-de-salmon-con-aguacate.jpg",
  "tentaculos-de-pulpo-sobre-tartufo-de-patatas": "/assets/photos/dishes/tentaculos-de-pulpo-sobre-tartufo-de-patatas.jpg",
  "tiramisu": "/assets/photos/dishes/tiramisu.jpg",
  "tortillitas-de-camarones": "/assets/photos/dishes/tortillitas-de-camarones.jpg",
  "vieira-con-langostinos": "/assets/photos/dishes/vieira-con-langostinos.jpg",
};

export type DishSlug = keyof typeof DISH_PHOTOS;
