// AUTO-GENERATED by scripts/download-premium-photos.mjs.
export const PREMIUM = {
  "hero-restaurant": "/assets/photos/premium/hero-restaurant.jpg",
  "hero-table": "/assets/photos/premium/hero-table.jpg",
  "hero-beach": "/assets/photos/premium/hero-beach.jpg",
  "dish-seafood": "/assets/photos/premium/dish-seafood.jpg",
  "dish-paella": "/assets/photos/premium/dish-paella.jpg",
  "dish-tartare": "/assets/photos/premium/dish-tartare.jpg",
  "dish-oysters": "/assets/photos/premium/dish-oysters.jpg",
  "dish-grill": "/assets/photos/premium/dish-grill.jpg",
  "wine-pour": "/assets/photos/premium/wine-pour.jpg",
  "wine-bottles": "/assets/photos/premium/wine-bottles.jpg",
  "interior-warm": "/assets/photos/premium/interior-warm.jpg",
  "interior-glass": "/assets/photos/premium/interior-glass.jpg",
  "kitchen-chef": "/assets/photos/premium/kitchen-chef.jpg",
  "sea-horizon": "/assets/photos/premium/sea-horizon.jpg",
  "sea-waves": "/assets/photos/premium/sea-waves.jpg",
  "olive-oil": "/assets/photos/premium/olive-oil.jpg",
  "facade-evening": "/assets/photos/premium/facade-evening.jpg",
  "lemons-fresh": "/assets/photos/premium/lemons-fresh.jpg",
} as const;

export type PremiumKey = keyof typeof PREMIUM;
